name: 'Hashicrop Packer Deploy Golden Image'

on:
  push:
    branches: [ "master" ]
  pull_request:

env:
    GOLDEN_IMAGE_VERSION: ${{ github.run_number }}  

jobs:
  Golden-Image:
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout code
      uses: actions/checkout@v2
        
    - name: Install Packer
      run: |
        wget https://releases.hashicorp.com/packer/1.7.6/packer_1.7.6_linux_amd64.zip
        unzip packer_1.7.6_linux_amd64.zip
        sudo mv packer /usr/local/bin/
      shell: bash

    - name: Display Packer Version
      run: packer version

    - name: Run Packer Build
      run: |

          gcloud config set project playground-s-11-79d214a5
          
          gcloud auth activate-service-account cli-service-account-1@playground-s-11-79d214a5.iam.gserviceaccount.com --key-file=creden.json --project=playground-s-11-79d214a5
                  
          gcloud compute images list --project=playground-s-11-79d214a5 --filter="name~'my-golden-image-'" --format="value(name)" | xargs -I {} gcloud compute images delete {} --project=playground-s-11-79d214a5 --quiet
         
          packer validate -var "image_name=${{ secrets.GOLDEN_IMAGE_NAME }}-${GOLDEN_IMAGE_VERSION}" packer-demo.json
          packer build -var "image_name=${{ secrets.GOLDEN_IMAGE_NAME }}-${GOLDEN_IMAGE_VERSION}" packer-demo.json
          
  terraform-job2:
    runs-on: ubuntu-latest
    needs: Golden-Image
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.3   # Specify the desired Terraform version

      - name: Terraform Init
        run: terraform init
      
      - name: Terraform Format
        run: terraform fmt

      - name: Terraform Validation
        run: terraform validate
      
      - name: Terraform Planning
        run: terraform plan -var="image-name=${{ secrets.GOLDEN_IMAGE_NAME }}-${GOLDEN_IMAGE_VERSION}"  -var="instance-name=my-custom-image-${GOLDEN_IMAGE_VERSION}"
        
      - name: Terraform Apply
        run: terraform apply --auto-approve -var="image-name=${{ secrets.GOLDEN_IMAGE_NAME }}-${GOLDEN_IMAGE_VERSION}" -var="instance-name=instance-${{ secrets.GOLDEN_IMAGE_NAME }}-${GOLDEN_IMAGE_VERSION}"
    
