name: 'Hashicrop Packer Deploy Golden Image'

on:
  push:
    branches: [ "master" ]
  pull_request:

jobs:
  Golden-Image:
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout code
      uses: actions/checkout@v2
        
    -  name: Packer Install
       run: |
          curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
          sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
          sudo apt-get update && sudo apt-get install packer

    -  name: Packer Validation
       run: packer validate packer-demo.json

    -  name: Packer Build
       run: packer build packer-demo.json
       
             
    
